### ISSUE TITLE
Custom helpers registered in Apps throw an error if in custom partial

### ISSUE THREAD

**Issue by cleversprocket** [TryGhost/gscan#88] opened 2017-10-22 14:00 UTC
I’m seeing an issue with GScan and custom helpers registered by an app. GScan is throwing an error for the custom helpers but only when they are used in partials that are not one of the built in partials, like `navigation.hbs`.

So if I use a custom helper in `partials/my-partial.hbs` it will throw but it won’t throw in `partials/navigation.hbs`.

**Comment by ErisDS** [comment] 2017-10-23 08:36
Duplicate of #86

As per the other issue. It's not something our team is tracking or intending to build at the present moment, as Apps & custom helpers are not yet officially support - hence we close the issue. Happy to accept PRs though :)

**Closed by ErisDS** 2017-10-23 08:36 UTC

**Comment by cleversprocket** [comment] 2017-10-23 16:20
Hi @ErisDS, please reopen that issue and I would be happy to put in a PR.
