### ISSUE TITLE
[Bug] requireDir on Node 8

### ISSUE THREAD

**Issue by thonatos** [TryGhost/gscan#66] opened 2017-06-30 03:14 UTC
## env
- Node v8.0.0
- Ghost 1.0.0-beta.2 

## effect
could not active any theme, 🤣

## what

```
TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/thonatos/workspace/node/test/Ghost-1.0.0-beta.2/node_modules/require-dir/index.js:95:37)
    at Object.<anonymous> (/Users/thonatos/workspace/node/test/Ghost-1.0.0-beta.2/node_modules/gscan/lib/checker.js:8:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/thonatos/workspace/node/test/Ghost-1.0.0-beta.2/node_modules/gscan/lib/index.js:3:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.checkTheme [as check] (/Users/thonatos/workspace/node/test/Ghost-1.0.0-beta.2/core/server/themes/validate.js:10:17)
    at activeThemeHasLoaded (/Users/thonatos/workspace/node/test/Ghost-1.0.0-beta.2/core/server/themes/index.js:35:22)
    at tryCatcher (/Users/thonatos/workspace/node/test/Ghost-1.0.0-beta.2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/thonatos/workspace/node/test/Ghost-1.0.0-beta.2/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/thonatos/workspace/node/test/Ghost-1.0.0-beta.2/node_modules/bluebird/js/release/promise.js:569:18)

```

## why

```
"require-dir": "0.1.0"
```

- https://github.com/aseemk/requireDir/pull/46

## how 
- update requireDir to 0.3.2

**Comment by acburdine** [comment] 2017-06-30 03:20
@thonatos Thanks for the report, although I'm going to close it because it's a duplicate of #56.

**Closed by acburdine** 2017-06-30 03:20 UTC

**Comment by thonatos** [comment] 2017-06-30 03:26
got it. thanks.
