### ISSUE TITLE
Error showing for .page CSS class

### ISSUE THREAD

**Issue by biswajit-saha** [TryGhost/gscan#157] opened 2018-08-28 08:17 UTC
I know in body class `.page ` was replaced with `.page-template`. For that reason Gscan shows error.

But ` {{post_class}}` output a class nameed `page` .

Now if we try to style that page class in a css file with `.page` Gscan shows error. 
`Replace .page with the .page-template css class`

How to reproduce?
In page.hbs template use {{post_class}} like below, which will output `page` class.
```
<div class="{{post_class}}">
...........
</div>
```
Now in your css file use `page` class like below.
```
.page {
.....
}
```
Test with Gscan and you will get the error.

**Comment by kirrg001** [comment] 2018-09-06 09:47
Duplicate of https://github.com/TryGhost/gscan/issues/93

**Closed by kirrg001** 2018-09-06 09:47 UTC
